name: Build and Test

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go stable
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Build
        run: go build ./...
      - name: Test
        uses: robherley/go-test-action@v0
        with:
          testArguments: -race -coverprofile=coverage.out ./...
      - name: Coverage Summary
        run: go tool cover -func=coverage.out
      - name: Govulncheck
        uses: golang/govulncheck-action@v2
