name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go stable
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build
        run: go build ./...
      - name: Test
        uses: robherley/go-test-action@v0
